$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  platform:
    type: string
    enum: ["DNBSEQ","CAPILLARY", "LS454", "ILLUMINA", "SOLID", "HELICOS", "IONTORRENT", "ONT", "PACBIO"]
  
  ref:
    type: object
    properties:
      species:
        type: string
      build:
        type: string
      release:
        type: integer
      provider:
        type: string
    required:
      - species
      - build
      - release
      - provider

  filtering:
    type: object
    properties:
      vqsr:
        type: boolean
      hard:
        type: object
        properties:
          snvs:
            type: string
          indels:
            type: string
        required:
          - snvs
          - indels
    required:
      - vqsr
      - hard

  processing:
    type: object
    properties:
      remove-duplicates:
        type: boolean
      restrict-regions:
        type: string
      region-padding:
        type: integer
    required:
      - remove-duplicates

  params:
    type: object
    properties:
      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
          BaseRecalibrator:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
          ApplyBaseQualityRecalibrator:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
          GenotypeGVCFs:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
          VariantRecalibrator:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
          SelectVariants:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
          HardFiltering:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
          CombineGvcfs:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
        required:
          - HaplotypeCaller
          - BaseRecalibrator
          - ApplyBaseQualityRecalibrator
          - GenotypeGVCFs
          - VariantRecalibrator
          - SelectVariants
          - HardFiltering
          - CombineGvcfs
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: object
            properties:
              extra:
                type: string
              java:
                type: string
          MergeVcfs:
            type: object
            properties:
              merge_calls:
                type: string
              merge_variants:
                type: string
        required:
          - MarkDuplicates
          - MergeVcfs
      trimming:
        type: object
        properties:
          adapter-a:
            type: string
          adapter-g:
            type: string
          extra-pe:
            type: string
          extra-se:
            type: string
        required:
          - adapter-a
          - adapter-g
          - extra-se
          - extra-pe
      mapping:
        type: object
        properties:
          extra:
            type: string
        required:
          - extra
      vep:
        type: object
        properties:
          plugins:
            type: array
            items:
              type: string
          extra:
            type: string
        required:
          - plugins
          - extra
    required:
      - gatk
      - picard
      - trimming
      - mapping
      - vep

required:
  - samples
  - units
  - platform
  - ref
  - filtering
  - processing
  - params

